FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

RUN apt-get update && apt-get install -y apt-transport-https ca-certificates gnupg curl
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | \
  tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN apt-get update && apt-get install -y google-cloud-cli iputils-ping
RUN apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin kubectl
RUN apt-get install silversearcher-ag
RUN  echo 'deb [trusted=yes] http://ftp.de.debian.org/debian buster main' | tee -a vi /etc/apt/sources.list
RUN apt-get update && apt-get install -y kubectx wget

RUN pip install \
  datadog-api-client \
  google-cloud-container \
  google-api-python-client \
  cassandra-driver \
  isort \
  lz4 \
  coverage \
  ruff \
  pytz

COPY entrypoint-dev-container.sh /entrypoint.sh

# inastll k9s
RUN curl -sS https://webi.sh/k9s | sh

# Delta
RUN wget -q https://github.com/dandavison/delta/releases/download/0.18.2/git-delta_0.18.2_arm64.deb -O /tmp/git-delta.deb
RUN dpkg -i /tmp/git-delta.deb

# Install go, see go.dev for the latest version
RUN wget -q https://go.dev/dl/go1.23.2.linux-arm64.tar.gz -O /tmp/go.tar.gz
RUN tar -xzvf /tmp/go.tar.gz -C /usr/local
# RUN echo "--- Golang ---" >> ~/.zshrc
# RUN echo export GOPRIVATE=xxx >> ~/.zshrc
RUN echo export PATH=$HOME/go/bin:/usr/local/go/bin:$PATH >> ~/.zshrc
# Make ZSH the default shell for the current user in the container
# To check that the shell was indeed added: `chsh -l` and you should see it in the  list.
SHELL ["/bin/zsh", "-c"]
# RUN chsh -s /usr/bin/zsh

RUN chmod +x /entrypoint.sh
