# --- Oh My Zsh & Theme Setup ---
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="amuse"
export GCP_ZSH_THEME="dpoggi"
plugins=(git virtualenv iterm2 helm gcloud kubectl kubectx kube-ps1)
source $ZSH/oh-my-zsh.sh

# --- PATH Setup (using array for clarity) ---
typeset -U path
path=(
  /opt/homebrew/bin
  /opt/homebrew/sbin
  /usr/bin
  /usr/local/bin
  /bin
  /usr/sbin
  /sbin
  /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
  /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
  /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
  Library/Apple/usr/bin
  /Applications/CyberArk\ EPM.app/Contents/MacOS
  /System/Cryptexes/App/usr/bin
  /Applications/iTerm.app/Contents/Resources/utilities
  $HOME/.rd/bin
  /opt/homebrew/share/google-cloud-sdk/bin
  $HOME/Projects/dexcom-inc/sre/etc
  $HOME/Projects/clarkritchie/hot-garbage/bin
  # $(go env GOPATH)/bin
  /opt/homebrew/Cellar/mysql-client/8.3.0/bin
  /opt/homebrew/opt/libpq/bin
  $HOME/.local/bin
  $path
)
export PATH

# --- Aliases ---
alias ls="ls -la --color"
alias h='history'
alias git-sha='git rev-parse --short HEAD'
alias git-tags='git fetch origin --tags && git tag --list --sort=creatordate | tail -1'
alias current-tag='git describe --tags'
alias go-sre='cd ~/Projects/dexcom-inc/sre'
alias go-sre-libs='cd ~/Projects/dexcom-inc/sre-libs'
alias go-database='cd ~/Projects/dexcom-inc/database'
alias chart-bump="$HOME/Projects/clarkritchie/hot-garbage/bin/bump-helm-chart-version.zsh"
alias run-porcelain="git status --porcelain | grep '^??' | cut -c4- | xargs rm -rf"
alias fix-whitespace="sed -i '' 's/[[:space:]]*$//' $1"
alias alt-kubeconfig='export KUBECONFIG=~/.kube/config-alt'
alias kubeconfig='unset KUBECONFIG'
alias rm-bak-files="find . -name '*.bak' -exec rm -f {} \;"

# --- Functions ---
new-zshrc() {
  local src=~/Projects/clarkritchie/hot-garbage/configs/zshrc
  local dest=~/.zshrc
  local backup1='Library/Mobile Documents/iCloud~md~obsidian/Documents/Misc/obsidian-backup/Code/zshrc.zsh'
  echo "Installing new .zshrc"
  # redirect to silence command not found with path
  cp "$src" "$dest" && source "$dest" 2>/dev/null
  cp "$src" "${HOME}/$backup1"
}

# Kube PS1 prompt
# https://github.com/jonmosco/kube-ps1

# Function to show KUBECONFIG status in prompt if $KUBECONFIG is currently pointed elsewhere
kubeconfig-status() {
  local default_config="$HOME/.kube/config"
  if [[ -n "$KUBECONFIG" && "$KUBECONFIG" != "$default_config" ]]; then
    echo " ✴️ Alt KUBECONFIG"
  fi
}

# --- K8s Shortcuts ---
alias k=kubectl
alias klc="k config get-contexts"
alias kcc="k config current-context"
alias kuc="k config use-context"
alias kns="k get namespaces"
alias kdp='f() { k describe pod $1 };f'
alias kun='f() { k config set-context --current --namespace=$1 };f'
kgo() {
  pod=$(kubectl get pods --no-headers | awk "NR==$1" | awk '{print $1}')
  echo "Getting a shell in $pod"
  kubectl exec --stdin --tty "$pod" -- /bin/bash
}
# ...other k8s functions and aliases...

# --- OS-Specific Aliases ---
if [[ "$OSTYPE" == "darwin"* ]]; then
  alias argo-port-forward='k port-forward svc/argocd-platform-server 8082:80 -n argocd --context=$(kubectx -c) & sleep 2 && open http://localhost:8082'
else
  alias argo-port-forward='k port-forward svc/argocd-platform-server 8082:80 -n argocd --context=$(kubectx -c) & sleep 2 && xdg-open http://localhost:8082'
fi

# --- Miscellaneous ---
export TABSTOP=2
export CLOUDSDK_PYTHON_SITEPACKAGES=1

# --- Source Additional Configs ---
for file in "$HOME/Projects/etc/api-keys.zshrc" "$HOME/Projects/etc/clark-more-zsh.zshrc" "$HOME/Projects/etc/cloudsql-aliases.zshrc"; do
  [[ -f $file ]] && source $file
done

# --- rbenv ---
eval "$(rbenv init -)"

# --- Prompt Customization ---
PROMPT='$(kube_ps1)$(kubeconfig-status) '$PROMPT

# --- End of zshrc ---
