# --- Oh My Zsh & Theme Setup ---
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="amuse"
export GCP_ZSH_THEME="dpoggi"
plugins=(git virtualenv iterm2 helm gcloud kubectl kubectx kube-ps1)
source $ZSH/oh-my-zsh.sh

# --- PATH Setup (using array for clarity) ---
typeset -U path
path=(
  /opt/homebrew/bin
  /opt/homebrew/sbin
  /usr/bin
  /usr/local/bin
  /bin
  /usr/sbin
  /sbin
  /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
  /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
  /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
  Library/Apple/usr/bin
  /Applications/CyberArk\ EPM.app/Contents/MacOS
  /System/Cryptexes/App/usr/bin
  /Applications/iTerm.app/Contents/Resources/utilities
  $HOME/.rd/bin
  /opt/homebrew/share/google-cloud-sdk/bin
  $HOME/Projects/dexcom-inc/sre/etc
  $HOME/Projects/clarkritchie/hot-garbage/bin
  # $(go env GOPATH)/bin
  /opt/homebrew/Cellar/mysql-client/8.3.0/bin
  /opt/homebrew/opt/libpq/bin
  $HOME/.local/bin
  $path
  $HOME/Projects/clarkritchie/hot-garbage/bin
)
export PATH

# --- Aliases ---
alias alt-kubeconfig='export KUBECONFIG=~/.kube/config-alt'
alias chart-bump="$HOME/Projects/clarkritchie/hot-garbage/bin/bump-helm-chart-version.zsh"
alias create-pr='create-pr.zsh'
alias current-tag='git describe --tags'
alias fix-whitespace="sed -i '' 's/[[:space:]]*$//' $1"
alias get-argo-secret='k get secret argocd-initial-admin-secret -n argocd -o jsonpath="{.data}" | jq -r '\''to_entries[] | "\(.key): \(.value | @base64d)"'\'
alias git-sha='git rev-parse --short HEAD'
alias git-tags='git fetch origin --tags && git tag --list --sort=creatordate | tail -1'
alias go-database='cd ~/Projects/dexcom-inc/database'
alias go-sre='cd ~/Projects/dexcom-inc/sre'
alias go-sre-libs='cd ~/Projects/dexcom-inc/sre-libs'
alias h='history'
alias ls="ls -la --color"
alias no-alt-kubeconfig='unset KUBECONFIG'
alias rm-bak-files="find . -name '*.bak' -exec rm -f {} \;"
alias run-porcelain="git status --porcelain | grep '^??' | cut -c4- | xargs rm -rf"

# comment or uncomment the lines that makes Pulumi re-compile the Go binary
alias compile-on="sed -i '' '4,5 s/^/#/' Pulumi.yaml"
alias compile-off="sed -i '' '4,5 s/^#//' Pulumi.yaml"

# --- Functions ---
new-zshrc() {
  local src=~/Projects/clarkritchie/hot-garbage/configs/zshrc
  local dest=~/.zshrc
  local backup1='Library/Mobile Documents/iCloud~md~obsidian/Documents/Misc/obsidian-backup/Code/zshrc.zsh'
  echo "Installing new .zshrc"
  # redirect to silence command not found with path
  cp "$src" "$dest" && source "$dest" 2>/dev/null
  cp "$src" "${HOME}/$backup1"
}

# Function to decode and print all keys/values from a Kubernetes secret
kdec(){
   kubectl get secret $1 -o go-template='{{range $k,$v := .data}}{{printf "%s: " $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{"\n"}}{{end}}'
}

# Kube PS1 prompt
# https://github.com/jonmosco/kube-ps1

# Function to show KUBECONFIG status in prompt if $KUBECONFIG is currently pointed elsewhere
kubeconfig-status() {
  local default_config="$HOME/.kube/config"
  if [[ -n "$KUBECONFIG" && "$KUBECONFIG" != "$default_config" ]]; then
    echo " ✴️ Alt KUBECONFIG"
  fi
}

# --- K8s Shortcuts ---
alias k=kubectl
alias klc="k config get-contexts"
alias kcc="k config current-context"
alias kuc="k config use-context"
alias kns="k get namespaces"
alias kdp='f() { k describe pod $1 };f'
alias kun='f() { k config set-context --current --namespace=$1 };f'
kgo() {
  pod=$(kubectl get pods --no-headers | awk "NR==$1" | awk '{print $1}')
  echo "Getting a shell in $pod"
  kubectl exec --stdin --tty "$pod" -- /bin/bash
}
alias kevents='kubectl get events --sort-by=".metadata.creationTimestamp"'

# k logs pod/dexcom-datadog-operator-d96ddf49d-ccrnh | jq 'select(.level == "ERROR" and .logger != "controllers.DatadogGenericResource")'
# kerror() {
#   k logs "$1" | jq 'select(.level == "ERROR")'
# }



# --- OS-Specific Aliases ---

# if [[ "$OSTYPE" == "darwin"* ]]; then
#   alias argo-port-forward='k port-forward svc/argocd-platform-server 8082:80 -n argocd --context=$(kubectx -c) & sleep 2 && open http://localhost:8082'
# else
#   alias argo-port-forward='k port-forward svc/argocd-platform-server 8082:80 -n argocd --context=$(kubectx -c) & sleep 2 && xdg-open http://localhost:8082'
# fi

argo-port-forward() {
  get-argo-secret

  # Check if port-forward to localhost:8082 is already running
  RUNNING_PID=$(pgrep -f "kubectl port-forward svc/argocd-platform-server 8082:80 -n argocd")
  if [[ -n "$RUNNING_PID" ]]; then
    echo "Port-forward to localhost:8082 is already runnin with PID ${RUNNING_PID}. Exiting."
    return 1
  fi

  # Run port-forward and open browser based on OS
  if [[ "$OSTYPE" == "darwin"* ]]; then
    k port-forward svc/argocd-platform-server 8082:80 -n argocd --context=$(kubectx -c)
    # sleep 2 && open http://localhost:8082
  else
    k port-forward svc/argocd-platform-server 8082:80 -n argocd --context=$(kubectx -c)
    # sleep 2 && xdg-open http://localhost:8082
  fi
}

# --- Miscellaneous ---
export TABSTOP=2
export CLOUDSDK_PYTHON_SITEPACKAGES=1

# --- Source Additional Configs ---
for file in "$HOME/Projects/etc/api-keys.zshrc" "$HOME/Projects/etc/clark-more-zsh.zshrc" "$HOME/Projects/etc/cloudsql-aliases.zshrc"; do
  [[ -f $file ]] && source $file
done

# --- rbenv ---
eval "$(rbenv init -)"

# --- Prompt Customization ---
PROMPT='$(kube_ps1)$(kubeconfig-status) '$PROMPT

ip() {
  typeset -a ITERM_PROFILES=(
    "Default"
    # "idleToes"
    "Fairyfloss"
    "ToyChest"
    "GruvboxDark"
    "Purple Rain"
    "MaterialDark"
    "FrontEndDelight"
    "Jackie Brown"
  )

  setopt KSH_ARRAYS 2>/dev/null
  local index=$((RANDOM % ${#ITERM_PROFILES[@]}))
  local random_profile=${ITERM_PROFILES[$index]}
  echo -e "\033]50;SetProfile=$random_profile\a"
  unsetopt KSH_ARRAYS 2>/dev/null
}
ip
# --- End of zshrc ---
